
// This file has been generated by the GUI designer. Do not modify.
namespace Testy.Gui
{
	public partial class DlgExport
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Entry edFileName;
		
		private global::Gtk.Button btSaveAs;
		
		private global::Gtk.Label lblFrame;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.ComboBox cbFormat;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Testy.Gui.DlgExport
			this.Name = "Testy.Gui.DlgExport";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Testy.Gui.DlgExport.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.edFileName = new global::Gtk.Entry ();
			this.edFileName.CanFocus = true;
			this.edFileName.Name = "edFileName";
			this.edFileName.IsEditable = true;
			this.edFileName.InvisibleChar = '•';
			this.hbox2.Add (this.edFileName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.edFileName]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btSaveAs = new global::Gtk.Button ();
			this.btSaveAs.CanFocus = true;
			this.btSaveAs.Name = "btSaveAs";
			this.btSaveAs.UseStock = true;
			this.btSaveAs.UseUnderline = true;
			this.btSaveAs.Label = "gtk-save-as";
			this.hbox2.Add (this.btSaveAs);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btSaveAs]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.GtkAlignment2.Add (this.hbox2);
			this.frame1.Add (this.GtkAlignment2);
			this.lblFrame = new global::Gtk.Label ();
			this.lblFrame.Name = "lblFrame";
			this.lblFrame.LabelProp = "<b>File</b>";
			this.lblFrame.UseMarkup = true;
			this.frame1.LabelWidget = this.lblFrame;
			this.vbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.cbFormat = global::Gtk.ComboBox.NewText ();
			this.cbFormat.AppendText ("Text");
			this.cbFormat.AppendText ("Html");
			this.cbFormat.AppendText ("Csv");
			this.cbFormat.Name = "cbFormat";
			this.cbFormat.Active = 0;
			this.GtkAlignment4.Add (this.cbFormat);
			this.frame2.Add (this.GtkAlignment4);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = "<b>Format</b>";
			this.GtkLabel2.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel2;
			this.vbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			w1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Internal child Testy.Gui.DlgExport.ActionArea
			global::Gtk.HButtonBox w11 = this.ActionArea;
			w11.Name = "dialog1_ActionArea";
			w11.Spacing = 10;
			w11.BorderWidth = ((uint)(5));
			w11.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonCancel]));
			w12.Expand = false;
			w12.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonOk]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 178;
			this.Show ();
			this.btSaveAs.Clicked += new global::System.EventHandler (this.OnSaveAsClicked);
			this.cbFormat.Changed += new global::System.EventHandler (this.OnFormatChanged);
		}
	}
}
