
// This file has been generated by the GUI designer. Do not modify.
namespace Testy.Gui
{
	public partial class DlgTakeTest
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action goBackAction;
		
		private global::Gtk.Action goForwardAction;
		
		private global::Gtk.Action quitAction;
		
		private global::Gtk.Toolbar toolbar2;
		
		private global::Gtk.ScrolledWindow scrlQuestion;
		
		private global::Gtk.TextView txtQuestion;
		
		private global::Gtk.ComboBox cbAnswers;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.ComboBox cbQuestionNumber;
		
		private global::Gtk.Alignment alignment2;
		
		private global::Gtk.Label lblTitle;
		
		private global::Gtk.Label lblCorrect;
		
		private global::Gtk.Label lblNumber;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Testy.Gui.DlgTakeTest
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.goBackAction = new global::Gtk.Action ("goBackAction", null, null, "gtk-go-back");
			w1.Add (this.goBackAction, null);
			this.goForwardAction = new global::Gtk.Action ("goForwardAction", null, null, "gtk-go-forward");
			w1.Add (this.goForwardAction, null);
			this.quitAction = new global::Gtk.Action ("quitAction", null, null, "gtk-quit");
			w1.Add (this.quitAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Testy.Gui.DlgTakeTest";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Testy.Gui.DlgTakeTest.VBox
			global::Gtk.VBox w2 = this.VBox;
			w2.Name = "dialog1_VBox";
			w2.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='goBackAction' action='goBackAction'/><toolitem name='goForwardAction' action='goForwardAction'/><toolitem name='quitAction' action='quitAction'/></toolbar></ui>");
			this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
			this.toolbar2.Name = "toolbar2";
			this.toolbar2.ShowArrow = false;
			w2.Add (this.toolbar2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w2 [this.toolbar2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.scrlQuestion = new global::Gtk.ScrolledWindow ();
			this.scrlQuestion.Name = "scrlQuestion";
			this.scrlQuestion.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrlQuestion.Gtk.Container+ContainerChild
			this.txtQuestion = new global::Gtk.TextView ();
			this.txtQuestion.CanFocus = true;
			this.txtQuestion.Name = "txtQuestion";
			this.txtQuestion.Editable = false;
			this.scrlQuestion.Add (this.txtQuestion);
			w2.Add (this.scrlQuestion);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w2 [this.scrlQuestion]));
			w5.Position = 1;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.cbAnswers = global::Gtk.ComboBox.NewText ();
			this.cbAnswers.Name = "cbAnswers";
			w2.Add (this.cbAnswers);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w2 [this.cbAnswers]));
			w6.Position = 2;
			w6.Expand = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.cbQuestionNumber = global::Gtk.ComboBox.NewText ();
			this.cbQuestionNumber.Name = "cbQuestionNumber";
			this.hbox3.Add (this.cbQuestionNumber);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.cbQuestionNumber]));
			w7.Position = 0;
			w7.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hbox3.Add (this.alignment2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment2]));
			w8.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblTitle = new global::Gtk.Label ();
			this.lblTitle.Name = "lblTitle";
			this.lblTitle.LabelProp = "label48";
			this.hbox3.Add (this.lblTitle);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblTitle]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblCorrect = new global::Gtk.Label ();
			this.lblCorrect.Name = "lblCorrect";
			this.lblCorrect.LabelProp = "label47";
			this.hbox3.Add (this.lblCorrect);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblCorrect]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblNumber = new global::Gtk.Label ();
			this.lblNumber.Name = "lblNumber";
			this.lblNumber.LabelProp = "label5";
			this.hbox3.Add (this.lblNumber);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblNumber]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			w2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(w2 [this.hbox3]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Internal child Testy.Gui.DlgTakeTest.ActionArea
			global::Gtk.HButtonBox w13 = this.ActionArea;
			w13.Name = "dialog1_ActionArea";
			w13.Spacing = 10;
			w13.BorderWidth = ((uint)(5));
			w13.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13 [this.buttonCancel]));
			w14.Expand = false;
			w14.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13 [this.buttonOk]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 472;
			this.DefaultHeight = 422;
			this.Show ();
			this.goBackAction.Activated += new global::System.EventHandler (this.OnPrev);
			this.goForwardAction.Activated += new global::System.EventHandler (this.OnFwd);
			this.quitAction.Activated += new global::System.EventHandler (this.OnQuit);
			this.cbAnswers.Changed += new global::System.EventHandler (this.OnAnswerChanged);
			this.cbQuestionNumber.Changed += new global::System.EventHandler (this.OnQuestionNumberChanged);
		}
	}
}
