
// This file has been generated by the GUI designer. Do not modify.
namespace Testy.Gui
{
	public partial class DlgTest
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action goBackAction;
		private global::Gtk.Action goForwardAction;
		private global::Gtk.Action quitAction;
		private global::Gtk.Toolbar toolbar1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView txtQuestion;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView txtCorrection;
		private global::Gtk.ComboBox combobox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Label lblFile;
		private global::Gtk.Label lblCorrect;
		private global::Gtk.Label lblNumber;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Testy.Gui.DlgTest
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.goBackAction = new global::Gtk.Action ("goBackAction", null, null, "gtk-go-back");
			w1.Add (this.goBackAction, null);
			this.goForwardAction = new global::Gtk.Action ("goForwardAction", null, null, "gtk-go-forward");
			w1.Add (this.goForwardAction, null);
			this.quitAction = new global::Gtk.Action ("quitAction", null, null, "gtk-quit");
			w1.Add (this.quitAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Testy.Gui.DlgTest";
			this.Title = global::Mono.Unix.Catalog.GetString ("Test");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child Testy.Gui.DlgTest.VBox
			global::Gtk.VBox w2 = this.VBox;
			w2.Name = "dialog1_VBox";
			w2.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar1\'><toolitem name=\'goBackAction\' action=\'goBackAction\'/" +
				"><toolitem name=\'goForwardAction\' action=\'goForwardAction\'/><toolitem name=\'quit" +
				"Action\' action=\'quitAction\'/></toolbar></ui>"
			);
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			w2.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w2 [this.toolbar1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtQuestion = new global::Gtk.TextView ();
			this.txtQuestion.CanFocus = true;
			this.txtQuestion.Name = "txtQuestion";
			this.GtkScrolledWindow.Add (this.txtQuestion);
			w2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w2 [this.GtkScrolledWindow]));
			w5.Position = 1;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txtCorrection = new global::Gtk.TextView ();
			this.txtCorrection.CanFocus = true;
			this.txtCorrection.Name = "txtCorrection";
			this.GtkScrolledWindow1.Add (this.txtCorrection);
			w2.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w2 [this.GtkScrolledWindow1]));
			w7.Position = 2;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.combobox2 = global::Gtk.ComboBox.NewText ();
			this.combobox2.Name = "combobox2";
			w2.Add (this.combobox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w2 [this.combobox2]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w9.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblFile = new global::Gtk.Label ();
			this.lblFile.Name = "lblFile";
			this.lblFile.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox1.Add (this.lblFile);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblFile]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblCorrect = new global::Gtk.Label ();
			this.lblCorrect.Name = "lblCorrect";
			this.lblCorrect.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.hbox1.Add (this.lblCorrect);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblCorrect]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblNumber = new global::Gtk.Label ();
			this.lblNumber.Name = "lblNumber";
			this.lblNumber.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.hbox1.Add (this.lblNumber);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblNumber]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			w2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(w2 [this.hbox1]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Internal child Testy.Gui.DlgTest.ActionArea
			global::Gtk.HButtonBox w14 = this.ActionArea;
			w14.Name = "dialog1_ActionArea";
			w14.Spacing = 10;
			w14.BorderWidth = ((uint)(5));
			w14.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonCancel]));
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14 [this.buttonOk]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 473;
			this.DefaultHeight = 403;
			this.Show ();
		}
	}
}
